### ISSUE TITLE
AssertionError: False is not true

### ISSUE THREAD

**Issue by lyciss** [midas-tum/merlin#3] opened 2022-05-30 08:10 UTC
FAIL: test2d (merlinth.test.test_layers_complex_maxpool.TestMagnitudePool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/merlinth/test/test_layers_complex_maxpool.py", line 39, in test2d
    self._verify_shape((1, 5, 7, 2), (2, 2), (2, 2), (0, 0), (1, 1), 'valid')
  File "/opt/conda/lib/python3.8/site-packages/merlinth/test/test_layers_complex_maxpool.py", line 81, in _verify_shape
    self.assertTrue(np.sum(np.abs(np.array(out.shape) - np.array(out_backend.shape))) == 0)
AssertionError: False is not true

======================================================================
FAIL: test3d (merlinth.test.test_layers_complex_maxpool.TestMagnitudePool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/merlinth/test/test_layers_complex_maxpool.py", line 28, in test3d
    self._verify_shape((1, 5, 7, 7, 2), (2, 2, 2), (2, 2, 2), (0, 0, 0), (1, 1, 1), 'valid')
  File "/opt/conda/lib/python3.8/site-packages/merlinth/test/test_layers_complex_maxpool.py", line 81, in _verify_shape
    self.assertTrue(np.sum(np.abs(np.array(out.shape) - np.array(out_backend.shape))) == 0)
AssertionError: False is not true

**Comment by thomaskuestner** [comment] 2022-06-08 16:10
Thanks for letting us know. We are looking into it.

**Comment by thomaskuestner** [comment] 2022-06-23 15:33
We were intensively testing this on our side (various machines, with/without optox), but unfortunately couldn't reproduce your issue.
Could you please let us know some more details and facts about your system/environment? Thanks.

**Comment by thomaskuestner** [comment] 2022-07-28 14:46
I am closing it as there has been no reply. Let us know if this is still an issue.

**Closed as completed by thomaskuestner** 2022-07-28 14:46 UTC
